spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched
  rabbitmq:
    host: localhost
    port: 5672
    username: broker
    password: broker
    connection-timeout: 5s
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    web: debug
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"