spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched
  rabbitmq:
    host: localhost
    port: 5672
    username: broker
    password: broker
    connection-timeout: 5s
server:
  port: 8083
